### ISSUE TITLE
Crash when starting the app

### ISSUE THREAD

**Issue by Thewisem** [otakuhqz/Omega#71] opened 2021-05-04 04:14 UTC
## Description

I just opened the app and it crashed

## Expected Behavior

App should start

## Steps to Reproduce

1. Open the app
2.Wait
3.
4.

## Device and OS

* Device: Samsung Galaxy Tab A SM P555
* Android version: 7 Nougat
* Launcher version: 0.7.1
* Rom: Default

## Logcat

```
your log here
```
Build version: 0.7.1 
Current date: 2021-05-04 07:12:14 
Device: Samsung SM-P555 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: android.view.InflateException: Binary XML file line #56: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.android.quickstep.views.LauncherRecentsView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:347)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:25)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.java:93)
	at android.app.Activity.performCreate(Activity.java:6977)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/TaskStackListener;
	at com.android.systemui.shared.system.ActivityManagerWrapper.getInstance(ActivityManagerWrapper.java:99)
	at com.android.quickstep.RecentsModel.<init>(RecentsModel.java:75)
	at com.android.quickstep.RecentsModel.lambda$Qm7E187uPu5w6aJQIVw5cciOIrc(RecentsModel.java)
	at com.android.quickstep.-$$Lambda$RecentsModel$Qm7E187uPu5w6aJQIVw5cciOIrc.get(lambda)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:44)
	at com.android.quickstep.views.RecentsView.<init>(RecentsView.java:327)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:97)
	at com.android.quickstep.views.LauncherRecentsView.<init>(LauncherRecentsView.java:93)
	... 27 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.TaskStackListener" on path: DexPathList[[zip file "/data/app/com.saggitt.omega-1/base.apk"],nativeLibraryDirectories=[/data/app/com.saggitt.omega-1/lib/arm, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 35 more

**Comment by breversa** [comment] 2021-05-06 09:19
Duplicate of https://github.com/otakuhqz/Omega/issues/70

**Comment by otakuhqz** [comment] 2021-05-06 12:49
Only android 8+ is supported.

**Closed by otakuhqz** 2021-05-06 12:49 UTC
