### ISSUE TITLE
Per App Customized Icons are reset after Time

### ISSUE THREAD

**Issue by byteme-git** [otakuhqz/Omega#104] opened 2021-08-10 13:01 UTC
## Description
After some time, without any reason obvious for me, icons i set for an individual App are reset. There is no direct correlation with restarts or crashes of Omega and the timing varies. 

This is especially annoying when using an monotone icon pack. 

## Expected Behavior

App should keep the assigned Icon

## Actual Behavior

Custom Icon is reset

## Steps to Reproduce

Set a custom Icon for an app and after some time it will be reset.

## Device and OS
* Poco Phone F1
* Android 11
* Rom: Lineage OS with microG (18.1-20210726-microG-beryllium)
* Launcher version: 0.8.0  (from F-Droid Repo)

**Comment by Elbullazul** [comment] 2021-08-14 21:38
It also happens to me on a Samsung A50. I noticed it happens after an app is updated

**Comment by gr0ndpa** [comment] 2021-08-15 15:09
Hey!
Here the same behavior. Here it always happens, when I uninstall an app. Is 100% reproducible!
Xiaomi Mi 11 lite 5G
A11 GSI
Omega Launcher 0.8.0 from git

**Comment by otakuhqz** [comment] 2021-08-15 15:51
The issue is already fixed in v0.8.1. This issue will be closed when the new version is released.

**Comment by gr0ndpa** [comment] 2021-08-15 17:20
Thank you very much!!!!!

**Comment by otakuhqz** [comment] 2021-08-18 00:14
Fixed on v0.8.1

**Closed by otakuhqz** 2021-08-18 00:14 UTC
