### ISSUE TITLE
Number of Dock Icons displayed is reverting to 5 icons after restart

### ISSUE THREAD

**Issue by GaryOwhere** [otakuhqz/Omega#68] opened 2021-04-16 22:04 UTC
## Description

After a device restart, the number of Dock Icons displayed reverts to the default Icon Count (5 icons), even though the Dock / Icon Count number has been changed to be more than 5 prior to the device restart.

This issue occurs in the **Developer** version (0.8.0 build 150), but does **not** occur in the **Release** version (0.7.1).

## Expected Behavior

The number of Dock Icons displayed should be equal to the Dock / Icon Count setting after a device restart.

## Actual Behavior

After a device restart, the Dock only displays up to 5 icons after a device restart. The value of the Home Settings / Dock / Icon Count does **not** change after the restart.

## Steps to Reproduce

1.  Change the Home Settings/ Dock / Icon Count from the default of 5 to a different value (for example, 7).
2.  Add icons to the Dock, up to the maximum number of icons set in the Dock / Icon Count in step 1.
3.  Restart the device.
4.  The number of icons displayed in the Dock is only 5, even though the Dock / Icon Count value has NOT changed to 5.

## Build information:
Package: com.saggitt.omega.dev 
Version: v0.8.0 (build 150)
Flavor: aospWithQuickstepOmega (debug)
Build date: 2021-04-14T03:33Z
ISource: com.google.android.packageinstaller
Manufacturer : Google
Model : Pixel 4a
OS Version : Android 11

**Comment by otakuhqz** [comment] 2021-04-17 14:35
I have been able to reproduce this bug and it looks like  the issue is when the icons are loaded. It will be fixed in the next days.

**Comment by GaryOwhere** [comment] 2021-04-17 17:25
> I have been able to reproduce this bug and it looks like the issue is when the icons are loaded. It will be fixed in the next days.

Thanks, @otakuhqz .  Nice work on Omega Launcher!

**Closed** 2021-04-23 04:10 UTC
Labels: bug
