### ISSUE TITLE
Pressing on app icon make it disappear

### ISSUE THREAD

**Issue by KrisadaFantasy** [otakuhqz/Omega#88] opened 2021-06-12 02:19 UTC
## Description
Pressing or dragging app icon will make it disappear.

## Expected Behaviour
App icon is appear throughout all interaction.

## Actual Behaviour
The icon disappear. If only pressing, it will be invisible until trelease. If dragging, it will be invisible until you drop it.

If the icon follow the shape in customise icons setting, it will only disappear for a very shot period and reappear as you press it. If it is not (use its own icon or customised icons from icon pack or gallery) it will disappear until you release it.

Using any shape other than circular will have the icon shape revert to circular while you press or drag it.

## Steps to Reproduce
Totally disappear while pressing or dragging: Pressing or dragging any customised icon that is not follow icon shape setting.
Disappear very briefly: Pressing or dragging any icon that follow non-circular icon shape setting
Revert to circular icon: Pressing or dragging any icon that follow circular icon shape setting 

## Device and OS

* Device: MiA3
* Android version: 11
* Launcher version: 0.8.0
* Rom: MiA3 Android One Stock Rom

**Comment by Oymate** [comment] 2021-07-19 12:38
Build version: 0.8.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-07-19 18:34:49  
OS version: Android 10 (SDK 29) 
 
Stack trace:  
android.view.InflateException: Binary XML file line #26 in com.saggitt.omega:layout/fragment_icon_customization: Binary XML file line #23 in com.saggitt.omega:layout/desktop_preview: Error inflating class com.saggitt.omega.icons.PreviewFrameView
Caused by: android.view.InflateException: Binary XML file line #23 in com.saggitt.omega:layout/desktop_preview: Error inflating class com.saggitt.omega.icons.PreviewFrameView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1237)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at com.saggitt.omega.OmegaLayoutInflater.inflate(OmegaLayoutInflater.kt:94)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.saggitt.omega.icons.IconCustomizeFragment.onCreateView(IconCustomizeFragment.kt:63)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7923)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3335)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: Permission android.permission.READ_EXTERNAL_STORAGE denied for package com.saggitt.omega
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:843)
	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:483)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:437)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:414)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:568)
	at com.saggitt.omega.wallpaper.WallpaperPreviewProvider.loadWallpaper(WallpaperPreviewProvider.kt:67)
	at com.saggitt.omega.wallpaper.WallpaperPreviewProvider.getWallpaper(WallpaperPreviewProvider.kt:55)
	at com.saggitt.omega.icons.PreviewFrameView.<init>(PreviewFrameView.kt:152)
	at com.saggitt.omega.icons.PreviewFrameView.<init>(PreviewFrameView.kt:37)
	at com.saggitt.omega.icons.PreviewFrameView.<init>(Unknown Source:6)
	... 36 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1654)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1632)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1712)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1781)
	at com.android.server.wallpaper.WallpaperManagerService.getWallpaper(WallpaperManagerService.java:2164)

**Comment by otakuhqz** [comment] 2021-08-18 00:16
Fixed on v0.8.1

**Closed by otakuhqz** 2021-08-18 00:16 UTC
